# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb0b0cdabfd014aeeb3ec5158cbdff2057744705e396dc062edf7ef29bb2dd1b573abb04ddd2f3c0a1b1715264d10f486106c62a81ed5e29efb2cf846015fda5

test:
  secret_key_base: 7412f8028391150bdf82cfdbcb7330dab4e77547d14f3039d441cfc7c946ad3290bf6753ca398435ebda226bb353d3ed6f5ec7f6d402c045d28e1db2862dc0c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
